
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


public class MoChaM extends javax.swing.JFrame implements Runnable{

int hour,minute,second;
  
    
    public MoChaM() {
        initComponents();
        Thread t = new Thread (this);
        t.start();// start thread go for run method for implementation
        
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnCoin500 = new javax.swing.JButton();
        jbtnCoin200 = new javax.swing.JButton();
        jbtnUang1000 = new javax.swing.JButton();
        jbtn1000Coin = new javax.swing.JButton();
        jbtnUang2000 = new javax.swing.JButton();
        jbtnUang5000 = new javax.swing.JButton();
        jbtnUang10000 = new javax.swing.JButton();
        jbtnUang20000 = new javax.swing.JButton();
        jbtnUang50000 = new javax.swing.JButton();
        jbtnUang75000 = new javax.swing.JButton();
        jbtnUang100000 = new javax.swing.JButton();
        jbtnCoin100 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jbtn7 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();
        jbtnTitik = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jbtnReset = new javax.swing.JButton();
        jbtnPay = new javax.swing.JButton();
        jbtnRemove = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jbtnReset1 = new javax.swing.JButton();
        jbtnExit1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtChange = new javax.swing.JTextField();
        jtxtDisplay = new javax.swing.JTextField();
        jcboPayment = new javax.swing.JComboBox<>();
        jtxtBarCode = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        time = new javax.swing.JLabel();
        TimeIn24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(125, 157, 156));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnCoin500.setBackground(new java.awt.Color(228, 220, 207));
        jbtnCoin500.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnCoin500.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/500C.png"))); // NOI18N
        jbtnCoin500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCoin500ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnCoin500, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 100, 100));

        jbtnCoin200.setBackground(new java.awt.Color(228, 220, 207));
        jbtnCoin200.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnCoin200.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/200C.png"))); // NOI18N
        jbtnCoin200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCoin200ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnCoin200, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 100, 100));

        jbtnUang1000.setBackground(new java.awt.Color(228, 220, 207));
        jbtnUang1000.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnUang1000.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1000.png"))); // NOI18N
        jbtnUang1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUang1000ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnUang1000, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 100, 100));

        jbtn1000Coin.setBackground(new java.awt.Color(228, 220, 207));
        jbtn1000Coin.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn1000Coin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1000C.png"))); // NOI18N
        jbtn1000Coin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1000CoinActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn1000Coin, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 100, 100));

        jbtnUang2000.setBackground(new java.awt.Color(228, 220, 207));
        jbtnUang2000.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnUang2000.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/2000.png"))); // NOI18N
        jbtnUang2000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUang2000ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnUang2000, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 100, 100));

        jbtnUang5000.setBackground(new java.awt.Color(228, 220, 207));
        jbtnUang5000.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnUang5000.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/5000.png"))); // NOI18N
        jbtnUang5000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUang5000ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnUang5000, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, 100));

        jbtnUang10000.setBackground(new java.awt.Color(228, 220, 207));
        jbtnUang10000.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnUang10000.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/10000.png"))); // NOI18N
        jbtnUang10000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUang10000ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnUang10000, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 100, 100));

        jbtnUang20000.setBackground(new java.awt.Color(228, 220, 207));
        jbtnUang20000.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnUang20000.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/20000.png"))); // NOI18N
        jbtnUang20000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUang20000ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnUang20000, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 100, 100));

        jbtnUang50000.setBackground(new java.awt.Color(228, 220, 207));
        jbtnUang50000.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnUang50000.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/50000.png"))); // NOI18N
        jbtnUang50000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUang50000ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnUang50000, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 100, 100));

        jbtnUang75000.setBackground(new java.awt.Color(228, 220, 207));
        jbtnUang75000.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnUang75000.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/75000.png"))); // NOI18N
        jbtnUang75000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUang75000ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnUang75000, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 100, 100));

        jbtnUang100000.setBackground(new java.awt.Color(228, 220, 207));
        jbtnUang100000.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnUang100000.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/100000.png"))); // NOI18N
        jbtnUang100000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUang100000ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnUang100000, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 100, 100));

        jbtnCoin100.setBackground(new java.awt.Color(228, 220, 207));
        jbtnCoin100.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnCoin100.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/100C.png"))); // NOI18N
        jbtnCoin100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCoin100ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnCoin100, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 750, 280));

        jPanel2.setBackground(new java.awt.Color(125, 157, 156));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn7.setText("7");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 90));

        jbtn8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 70, 90));

        jbtn6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 70, 90));

        jbtn5.setBackground(new java.awt.Color(240, 235, 227));
        jbtn5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 70, 90));

        jbtn4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn4.setText("4");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 70, 90));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton7.setText("7");
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 70, 90));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton8.setText("7");
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 70, 90));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton9.setText("7");
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 70, 90));

        jbtnC.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnC.setText("C");
        jbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 70, 90));

        jbtnTitik.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnTitik.setText(".");
        jbtnTitik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTitikActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnTitik, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 70, 90));

        jbtn0.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn0.setText("0");
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 70, 90));

        jbtn1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 70, 90));

        jbtn2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 70, 90));

        jbtn3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn3.setText("3");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 70, 90));

        jbtn9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 70, 90));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 300, 440));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Qty", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 310, 360));

        jPanel4.setBackground(new java.awt.Color(125, 157, 156));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(125, 157, 156));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 150, 50));

        jbtnPay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPay.setText("Pay");
        jbtnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPayActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 50));

        jbtnRemove.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnRemove.setText("Remove");
        jbtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 150, 50));

        jbtnPrint.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 150, 50));

        jbtnReset1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnReset1.setText("Reset");
        jbtnReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReset1ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnReset1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 150, 50));

        jbtnExit1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnExit1.setText("Exit");
        jbtnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExit1ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 370, 40));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, 420, 160));

        jPanel5.setBackground(new java.awt.Color(125, 157, 156));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Total");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("SubTotal");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Tax");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel5.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 190, -1));

        jtxtSubTotal.setEditable(false);
        jtxtSubTotal.setBackground(new java.awt.Color(255, 255, 255));
        jtxtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel5.add(jtxtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 190, -1));

        jtxtTax.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel5.add(jtxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 190, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 420, 160));

        jPanel6.setBackground(new java.awt.Color(125, 157, 156));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Cash");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Change");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Payment Method");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jtxtChange.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel6.add(jtxtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 180, -1));

        jtxtDisplay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel6.add(jtxtDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 180, -1));

        jcboPayment.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jcboPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Visa Card", "Master Card", " " }));
        jcboPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboPaymentActionPerformed(evt);
            }
        });
        jPanel6.add(jcboPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 180, 30));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 420, 160));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 1380, 220));

        jtxtBarCode.setFont(new java.awt.Font("barcode font", 1, 60)); // NOI18N
        jtxtBarCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBarCodeActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtBarCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 310, 80));

        jPanel7.setBackground(new java.awt.Color(87, 111, 114));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        time.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        TimeIn24.setFont(new java.awt.Font("Tahoma", 1, 110)); // NOI18N
        TimeIn24.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.add(TimeIn24, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 540, 90));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 750, 140));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtBarCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBarCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBarCodeActionPerformed
    
    
    
//================================Mata Uang===================================//
    
    private void jbtnCoin200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCoin200ActionPerformed
       
    double PriceOfItem = 200;
    
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.addRow(new Object[]{"200 Rupiah", "1", PriceOfItem });
    ItemCost();
    
    }//GEN-LAST:event_jbtnCoin200ActionPerformed

    
    
    
    
    
    
  
    
//================================FUNCTION ItemCost===================================//    
    

public void ItemCost()    
{
    double sum = 0;
    
    for (int i = 0; i < jTable1.getRowCount(); i++)
    
    {
        sum = sum + Double.parseDouble (jTable1.getValueAt (i, 2).toString());
    }
    
    jtxtSubTotal.setText(Double.toString(sum));
    double cTotal1 = Double.parseDouble(jtxtSubTotal.getText());
    
    double cTax = (cTotal1 * 1)/100;
    
    String iTaxTotal = String.format("Rp %.1f", cTax);  //Hitung Tax
    jtxtTax.setText(iTaxTotal);
    
    String iSubTotal = String.format("Rp %.1f", cTotal1); //Hitung SubTotal
    jtxtSubTotal.setText(iSubTotal);
   
    String iTotal = String.format("Rp %.1f", cTotal1 + cTax); //Hitung Total
    jtxtTotal.setText(iTotal);
    
    String BarCode = String.format("Total is %.1f", cTotal1 + cTax); //Hitung Total
    jtxtBarCode.setText(BarCode);
    
    
}    


//================================FUNCTION Change===================================//    
    

public void Change()    
{
    double sum = 0;
    double tax = 1;
    double cash = Double.parseDouble(jtxtDisplay.getText());
    
    for (int i = 0; i < jTable1.getRowCount(); i++)
    
    {
        sum = sum + Double.parseDouble (jTable1.getValueAt (i, 2).toString());
    }
    
    double cTax = (sum * 1)/100;
    double cChange = (cash - (sum + cTax) );
    
    String ChangeGiven = String.format("Rp %.1f", cChange);
    jtxtChange.setText(ChangeGiven);
    
    
}






    
//================================BUTTON===================================//
    
    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        
        String EnterNumber = jtxtDisplay.getText();
        
        if (EnterNumber == "")
        {
          jtxtDisplay.setText(jbtn7.getText());
        } 
        
        else
        {
            EnterNumber = jtxtDisplay.getText()+ jbtn7.getText();
            jtxtDisplay.setText(EnterNumber);
        }
       
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        
        String EnterNumber = jtxtDisplay.getText();
        
        if (EnterNumber == "")
        {
          jtxtDisplay.setText(jbtn8.getText());
        } 
        
        else
        {
            EnterNumber = jtxtDisplay.getText()+ jbtn8.getText();
            jtxtDisplay.setText(EnterNumber);
        }
        
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
       
        String EnterNumber = jtxtDisplay.getText();
        
        if (EnterNumber == "")
        {
          jtxtDisplay.setText(jbtn9.getText());
        } 
        
        else
        {
            EnterNumber = jtxtDisplay.getText()+ jbtn9.getText();
            jtxtDisplay.setText(EnterNumber);
        }
        
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        
        String EnterNumber = jtxtDisplay.getText();
        
        if (EnterNumber == "")
        {
          jtxtDisplay.setText(jbtn4.getText());
        } 
        
        else
        {
            EnterNumber = jtxtDisplay.getText()+ jbtn4.getText();
            jtxtDisplay.setText(EnterNumber);
        }
        
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
       
        String EnterNumber = jtxtDisplay.getText();
        
        if (EnterNumber == "")
        {
          jtxtDisplay.setText(jbtn5.getText());
        } 
        
        else
        {
            EnterNumber = jtxtDisplay.getText()+ jbtn5.getText();
            jtxtDisplay.setText(EnterNumber);
        }
        
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        
        String EnterNumber = jtxtDisplay.getText();
        
        if (EnterNumber == "")
        {
          jtxtDisplay.setText(jbtn6.getText());
        } 
        
        else
        {
            EnterNumber = jtxtDisplay.getText()+ jbtn6.getText();
            jtxtDisplay.setText(EnterNumber);
        }
        
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        
        String EnterNumber = jtxtDisplay.getText();
        
        if (EnterNumber == "")
        {
          jtxtDisplay.setText(jbtn1.getText());
        } 
        
        else
        {
            EnterNumber = jtxtDisplay.getText()+ jbtn1.getText();
            jtxtDisplay.setText(EnterNumber);
        }
        
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
        
        String EnterNumber = jtxtDisplay.getText();
        
        if (EnterNumber == "")
        {
          jtxtDisplay.setText(jbtn2.getText());
        } 
        
        else
        {
            EnterNumber = jtxtDisplay.getText()+ jbtn2.getText();
            jtxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        
        String EnterNumber = jtxtDisplay.getText();
        
        if (EnterNumber == "")
        {
          jtxtDisplay.setText(jbtn3.getText());
        } 
        
        else
        {
            EnterNumber = jtxtDisplay.getText()+ jbtn3.getText();
            jtxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
       
        String EnterNumber = jtxtDisplay.getText();
        
        if (EnterNumber == "")
        {
          jtxtDisplay.setText(jbtn0.getText());
        } 
        
        else
        {
            EnterNumber = jtxtDisplay.getText()+ jbtn0.getText();
            jtxtDisplay.setText(EnterNumber);
        }
        
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtnTitikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTitikActionPerformed
        
         if (! jtxtDisplay.getText().contains("."))
         {
             jtxtDisplay.setText(jtxtDisplay.getText()+ jbtnTitik.getText());
         }
    }//GEN-LAST:event_jbtnTitikActionPerformed

        
    private void jbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCActionPerformed
        
        jtxtDisplay.setText("");
        jtxtChange.setText("");
        
    }//GEN-LAST:event_jbtnCActionPerformed

    
    
    
    
    
    
//================================Mata Uangg===================================// 
    
    
    
    private void jbtnCoin100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCoin100ActionPerformed
    
    double PriceOfItem = 100;
    
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.addRow(new Object[]{"100 Rupiah", "1", PriceOfItem });
    ItemCost();
    
    
    }//GEN-LAST:event_jbtnCoin100ActionPerformed

    private void jbtnCoin500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCoin500ActionPerformed
     
    double PriceOfItem = 500;
    
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.addRow(new Object[]{"500 Rupiah", "1", PriceOfItem });
    ItemCost();
    
    }//GEN-LAST:event_jbtnCoin500ActionPerformed

    private void jbtn1000CoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1000CoinActionPerformed
    
    double PriceOfItem = 1000;
    
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.addRow(new Object[]{"1000 Rupiah", "1", PriceOfItem });
    ItemCost();
    
    }//GEN-LAST:event_jbtn1000CoinActionPerformed

    private void jbtnUang1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUang1000ActionPerformed
    
    double PriceOfItem = 1000;
    
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.addRow(new Object[]{"1000 Rupiah", "1", PriceOfItem });
    ItemCost();
    
    }//GEN-LAST:event_jbtnUang1000ActionPerformed

    private void jbtnUang2000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUang2000ActionPerformed
    
    double PriceOfItem = 2000;
    
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.addRow(new Object[]{"2000 Rupiah", "1", PriceOfItem });
    ItemCost();
    }//GEN-LAST:event_jbtnUang2000ActionPerformed

    private void jbtnUang5000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUang5000ActionPerformed
    
    double PriceOfItem = 5000;
    
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.addRow(new Object[]{"5000 Rupiah", "1", PriceOfItem });
    ItemCost();
    
    }//GEN-LAST:event_jbtnUang5000ActionPerformed

    private void jbtnUang10000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUang10000ActionPerformed
    
    double PriceOfItem = 10000;
    
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.addRow(new Object[]{"10000 Rupiah", "1", PriceOfItem });
    ItemCost();
    }//GEN-LAST:event_jbtnUang10000ActionPerformed

    private void jbtnUang20000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUang20000ActionPerformed
    
    double PriceOfItem = 20000;
    
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.addRow(new Object[]{"20000 Rupiah", "1", PriceOfItem });
    ItemCost();
    }//GEN-LAST:event_jbtnUang20000ActionPerformed

    private void jbtnUang50000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUang50000ActionPerformed
    
    double PriceOfItem = 50000;
    
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.addRow(new Object[]{"50000 Rupiah", "1", PriceOfItem });
    ItemCost();
    }//GEN-LAST:event_jbtnUang50000ActionPerformed

    private void jbtnUang75000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUang75000ActionPerformed
    
    double PriceOfItem = 75000;
    
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.addRow(new Object[]{"75000 Rupiah", "1", PriceOfItem });
    ItemCost();
    }//GEN-LAST:event_jbtnUang75000ActionPerformed

    private void jbtnUang100000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUang100000ActionPerformed
    
    double PriceOfItem = 100000;
    
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.addRow(new Object[]{"100000 Rupiah", "1", PriceOfItem });
    ItemCost();
    }//GEN-LAST:event_jbtnUang100000ActionPerformed

    
    
    
    
    
    
//================================PAYMENT===================================//     
    
    private void jbtnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPayActionPerformed
       
     if (jcboPayment.getSelectedItem().equals ("Cash"))
     {
         Change();
     }
     else
     {
         jtxtChange.setText("");
         jtxtDisplay.setText("");
      
     }
    }//GEN-LAST:event_jbtnPayActionPerformed
    
    private void jcboPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcboPaymentActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
       
        
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.setRowCount(0);
       
       jtxtChange.setText("");
       jtxtDisplay.setText("");
       jtxtTotal.setText("");
       jtxtSubTotal.setText("");
       jtxtTax.setText("");
       jtxtBarCode.setText("");
       
       
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
      
       MessageFormat header = new MessageFormat("Receipt");
       MessageFormat footer = new MessageFormat("Receipt {0, number, integer}");
       
       try
       {
          jTable1.print(JTable.PrintMode.NORMAL,header,footer); 
         
       }    
       
          catch (java.awt.print.PrinterException e)
           
       {
          System.err.format("Tidak Ada Receipt", e.getMessage()); 
       }    
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveActionPerformed
      
      DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
      
      int RemoveItem = jTable1.getSelectedRow();
      
      if (RemoveItem >= 0)
      {
          model.removeRow(RemoveItem);
      }
      
      ItemCost();
      
        if (jcboPayment.getSelectedItem().equals ("Cash"))
     {
         Change();
     }
     else
     {
         jtxtChange.setText("");
         jtxtDisplay.setText("");
      
     }
     
     
    }//GEN-LAST:event_jbtnRemoveActionPerformed

    private JFrame frame;
    private void jbtnReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReset1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnReset1ActionPerformed

    private void jbtnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExit1ActionPerformed
           
        frame = new JFrame("Exit");
        
        if (JOptionPane.showConfirmDialog(frame, "YES jika kamu mau keluar", "MoCha", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION);
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExit1ActionPerformed

    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoChaM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoChaM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoChaM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoChaM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MoChaM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TimeIn24;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn1000Coin;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnCoin100;
    private javax.swing.JButton jbtnCoin200;
    private javax.swing.JButton jbtnCoin500;
    private javax.swing.JButton jbtnExit1;
    private javax.swing.JButton jbtnPay;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnRemove;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnReset1;
    private javax.swing.JButton jbtnTitik;
    private javax.swing.JButton jbtnUang1000;
    private javax.swing.JButton jbtnUang10000;
    private javax.swing.JButton jbtnUang100000;
    private javax.swing.JButton jbtnUang2000;
    private javax.swing.JButton jbtnUang20000;
    private javax.swing.JButton jbtnUang5000;
    private javax.swing.JButton jbtnUang50000;
    private javax.swing.JButton jbtnUang75000;
    private javax.swing.JComboBox<String> jcboPayment;
    private javax.swing.JTextField jtxtBarCode;
    private javax.swing.JTextField jtxtChange;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while(true){
            Calendar cal = Calendar.getInstance();
            // get current hour minute and second
            hour = cal.get(Calendar.HOUR_OF_DAY);
            minute = cal.get(Calendar.MINUTE);
            second = cal.get(Calendar.SECOND);
            
            SimpleDateFormat sdf24 = new SimpleDateFormat("HH:mm:ss");
            Date dat = cal.getTime();
            String time24 = sdf24.format(dat);
            
            TimeIn24.setText(time24);
            
        }
    }

}
    

